[project]
name = "samat-bot"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "python-telegram-bot>=21",
    "python-dotenv>=1",
]

[dependency-groups]
dev = [
    "ruff>=0.9",
    "ty>=0.0.1",
    "watchdog[watchmedo]>=6",
]

[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "A002", "A003", "ANN", "ARG", "COM812", "D", "D211", "D213",
    "EM101", "FA102", "ISC001", "N818", "PLR2004", "PLW1508",
    "PT", "S101", "S104", "S701", "T201"
]
fixable = ["ALL"]

[tool.ty.environment]
python-version = "3.14"
